-- 04_create_initial_canonical_specs.sql
-- canonical層（標準仕様項目）と、マッピング用の同義語・パターン・単位変換のシード。
-- ここは「初期案」であり、レビュー後に行を追加・修正して 05 以降を再実行する運用を想定。

DELETE FROM canonical_specs;
DELETE FROM spec_synonyms;
DELETE FROM spec_patterns;
DELETE FROM unit_conversions;

-- ================================================================
-- 1. canonical_specs
--    priority: 1=コア比較 2=フル比較 3=参考
--    canonical_unit が NULL の項目はテキスト項目。
-- ================================================================
INSERT INTO canonical_specs VALUES
-- basic_info
('model_name',        '型式名',           'Model name',          'basic_info', NULL,   'text',    3, '製品の型式表記（products と重複するが raw 由来として保持）', FALSE),
('product_class',     '一般的な製品分類', 'Product class',       'basic_info', NULL,   'text',    3, 'Compact articulated loader など', FALSE),
('market_segment',    'SAL分類',          'Market segment',      'basic_info', NULL,   'text',    3, '調査用分類（SAL / テレスコありのSAL 等）', FALSE),
('power_type',        '動力区分',         'Power type',          'basic_info', NULL,   'text',    2, 'Diesel / Petrol / Electric', TRUE),
('sales_status',      '販売状況',         'Sales status',        'basic_info', NULL,   'text',    3, '現行 / 旧型 / Prototype', FALSE),
('product_url',       '製品URL',          'Product URL',         'basic_info', NULL,   'text',    3, NULL, FALSE),
('product_code',      '製品コード',       'Product code',        'basic_info', NULL,   'text',    3, NULL, FALSE),
-- weight
('operating_weight',          '運転質量',           'Operating weight',            'weight', 'kg', 'numeric', 1, 'オープンキャブ/標準構成の機体質量', TRUE),
('operating_weight_enclosed', '運転質量(キャブ付)', 'Operating weight (enclosed)', 'weight', 'kg', 'numeric', 3, NULL, TRUE),
-- engine
('engine_model',        'エンジン型式',   'Engine model',        'engine', NULL,  'text',    2, NULL, TRUE),
('engine_manufacturer', 'エンジンメーカー', 'Engine manufacturer', 'engine', NULL, 'text',    3, NULL, TRUE),
('engine_power',        'エンジン出力',   'Engine power',        'engine', 'kW',  'numeric', 1, 'グロス出力。kW を正とし hp は変換', TRUE),
('engine_torque',       '最大トルク',     'Peak torque',         'engine', 'Nm',  'numeric', 2, NULL, TRUE),
('engine_displacement', '排気量',         'Displacement',        'engine', 'cc',  'numeric', 2, NULL, TRUE),
('engine_cylinders',    '気筒数',         'Cylinders',           'engine', 'cyl', 'numeric', 3, NULL, TRUE),
('fuel_type',           '燃料種別',       'Fuel type',           'engine', NULL,  'text',    2, NULL, TRUE),
('fuel_tank_capacity',  '燃料タンク容量', 'Fuel tank capacity',  'engine', 'L',   'numeric', 3, NULL, TRUE),
('rated_engine_speed',  '定格回転数',     'Rated engine speed',  'engine', 'rpm', 'numeric', 3, NULL, TRUE),
-- electrical（電動パワートレイン・電装）
('battery_capacity',         'バッテリー容量',       'Battery capacity',        'electrical', 'kWh', 'numeric', 2, '走行用バッテリー。kWh を正とする', TRUE),
('starter_battery_capacity', '補機バッテリー容量',   'Starter battery capacity', 'electrical', 'Ah', 'numeric', 3, '始動用鉛バッテリー等（kWh の走行用と区別）', TRUE),
('battery_type',             'バッテリー種別',       'Battery type',            'electrical', NULL,  'text',    3, NULL, TRUE),
('charge_time',              '充電時間',             'Charge time',             'electrical', 'h',   'numeric', 2, NULL, TRUE),
('motor_power_drive',        '走行モーター出力',     'Drive motor power',       'electrical', 'kW',  'numeric', 2, NULL, TRUE),
('motor_power_implement',    '作業機モーター出力',   'Implement motor power',   'electrical', 'kW',  'numeric', 2, NULL, TRUE),
('operation_time',           '連続稼働時間',         'Operation time',          'electrical', 'h',   'numeric', 3, NULL, TRUE),
('system_voltage',           'システム電圧',         'System voltage',          'electrical', 'V',   'numeric', 3, NULL, TRUE),
-- compliance
('emissions_standard', '排出ガス規格', 'Emissions standard', 'compliance', NULL, 'text', 2, 'Stage V / Tier 4 Final 等', TRUE),
('rops_fops',          'ROPS/FOPS',    'ROPS/FOPS',          'compliance', NULL, 'text', 3, NULL, TRUE),
-- dimensions
('overall_length',             '全長',             'Overall length',            'dimensions', 'mm', 'numeric', 1, 'バケットなし', TRUE),
('overall_length_with_bucket', '全長(バケット付)', 'Length with bucket',        'dimensions', 'mm', 'numeric', 3, NULL, TRUE),
('overall_width',              '全幅',             'Overall width',             'dimensions', 'mm', 'numeric', 1, NULL, TRUE),
('overall_height',             '全高',             'Overall height',            'dimensions', 'mm', 'numeric', 1, 'ROPS/キャブ上端まで', TRUE),
('wheelbase',                  'ホイールベース',   'Wheelbase',                 'dimensions', 'mm', 'numeric', 2, NULL, TRUE),
('ground_clearance',           '最低地上高',       'Ground clearance',          'dimensions', 'mm', 'numeric', 3, NULL, TRUE),
('turning_radius_inner',       '旋回半径(内側)',   'Turning radius (inner)',    'dimensions', 'mm', 'numeric', 2, NULL, TRUE),
('turning_radius_outer',       '旋回半径(外側)',   'Turning radius (outer)',    'dimensions', 'mm', 'numeric', 2, NULL, TRUE),
('seat_height',                'シート高',         'Seat height',               'dimensions', 'mm', 'numeric', 3, NULL, TRUE),
('dump_height',                'ダンプ高',         'Dump height',               'dimensions', 'mm', 'numeric', 2, NULL, TRUE),
('dump_angle',                 'ダンプ角',         'Dump angle',                'dimensions', '°',  'numeric', 3, NULL, TRUE),
('articulation_angle',         '関節角',           'Articulation angle',        'dimensions', '°',  'numeric', 3, NULL, TRUE),
-- performance
('lift_height',              'リフト高(ヒンジピン)', 'Lift height (hinge pin)',   'performance', 'mm',    'numeric', 1, 'バケットヒンジピン高さ', TRUE),
('lift_capacity',            'リフト容量',           'Lift capacity',             'performance', 'kg',    'numeric', 1, '最大持ち上げ能力（定格ではない場合あり。notes 参照）', TRUE),
('tipping_load_straight',    '転倒荷重(直進)',       'Tipping load (straight)',   'performance', 'kg',    'numeric', 1, 'ISO 直進時', TRUE),
('tipping_load_articulated', '転倒荷重(屈曲)',       'Tipping load (articulated)', 'performance', 'kg',   'numeric', 2, NULL, TRUE),
('tipping_load',             '転倒荷重(条件不明)',   'Tipping load (unspecified)', 'performance', 'kg',   'numeric', 1, '直進/屈曲の条件が資料に明記されないもの。straight とは別列で比較', TRUE),
('rated_operating_capacity', '定格運転容量(直進)',   'Rated operating capacity',  'performance', 'kg',    'numeric', 1, 'ROC。通常は転倒荷重の50%', TRUE),
('rated_operating_capacity_articulated', '定格運転容量(屈曲)', 'ROC (articulated)', 'performance', 'kg',  'numeric', 2, NULL, TRUE),
('breakout_force',           'ブレークアウト力',     'Breakout force',            'performance', 'kN',    'numeric', 2, NULL, TRUE),
('traction_force',           '牽引力',               'Traction force',            'performance', 'kN',    'numeric', 2, NULL, TRUE),
('pushing_force',            '押し出し力',           'Pushing force',             'performance', 'kN',    'numeric', 2, NULL, TRUE),
('max_travel_speed',         '最高速度',             'Max travel speed',          'performance', 'km/h',  'numeric', 1, NULL, TRUE),
('ground_pressure',          '平均接地圧',           'Average ground pressure',   'performance', 'kg/m2', 'numeric', 3, NULL, TRUE),
('bucket_capacity',          'バケット容量',         'Bucket capacity',           'performance', 'm3',    'numeric', 2, NULL, TRUE),
('bucket_width',             'バケット幅',           'Bucket width',              'performance', 'mm',    'numeric', 3, NULL, TRUE),
('max_reach',                '最大リーチ',           'Max reach',                 'performance', 'mm',    'numeric', 3, NULL, TRUE),
('telescopic_boom',          'テレスコブーム',       'Telescopic boom',           'performance', NULL,    'text',    2, 'あり/なし/仕様表記', TRUE),
('telescopic_length',        'テレスコ長',           'Telescopic length',         'performance', 'mm',    'numeric', 3, NULL, TRUE),
-- hydraulics
('aux_hydraulic_flow',      '補助油圧流量',       'Aux hydraulic flow',        'hydraulics', 'L/min', 'numeric', 1, 'アタッチメント用油圧流量', TRUE),
('aux_hydraulic_pressure',  '補助油圧圧力',       'Aux hydraulic pressure',    'hydraulics', 'MPa',   'numeric', 1, NULL, TRUE),
('aux_hydraulic_flow_high', '補助油圧流量(ハイフロー)', 'High flow (optional)', 'hydraulics', 'L/min', 'numeric', 3, NULL, TRUE),
('hydraulic_system_capacity', '作動油量',         'Hydraulic system capacity', 'hydraulics', 'L',     'numeric', 3, NULL, TRUE),
('drive_hydraulic_system',  '走行系油圧システム', 'Drive hydraulic system',    'hydraulics', NULL,    'text',    3, NULL, TRUE),
('work_hydraulic_system',   '作業機系油圧システム', 'Work hydraulic system',   'hydraulics', NULL,    'text',    3, NULL, TRUE),
-- drivetrain
('transmission', 'トランスミッション', 'Transmission', 'drivetrain', NULL, 'text', 2, NULL, TRUE),
-- accessories
('standard_tires', '標準タイヤ',   'Standard tires', 'accessories', NULL, 'text', 2, NULL, TRUE),
('tire_tread',     'タイヤトレッド', 'Tire tread',   'accessories', NULL, 'text', 3, NULL, TRUE),
('wheel_size',     'ホイールサイズ', 'Wheel size',   'accessories', NULL, 'text', 3, NULL, TRUE),
-- warranty
('warranty', '保証', 'Warranty', 'warranty', NULL, 'text', 2, NULL, TRUE);

-- ================================================================
-- 2. spec_synonyms（確度の高い対応のみ。key は psn_item_key() 適用後）
--    match_type: exact = canonical の名称そのもの / synonym = 別名
-- ================================================================
INSERT INTO spec_synonyms (synonym_key, canonical_item, match_type, notes) VALUES
-- operating_weight
('運転質量', 'operating_weight', 'exact', NULL),
('運転質量_kg', 'operating_weight', 'synonym', 'Avant 横持ち列名'),
('operating weight', 'operating_weight', 'exact', NULL),
('operating weight / open cab', 'operating_weight', 'synonym', 'Case 型式別シート。オープンキャブを標準構成とみなす'),
('operating weight (open cab)', 'operating_weight', 'synonym', 'Case カタログ'),
('service weight', 'operating_weight', 'synonym', 'GIANT'),
('weight', 'operating_weight', 'synonym', 'MultiOne。機体質量を指す'),
('operating weight / enclosed cab', 'operating_weight_enclosed', 'synonym', NULL),
-- engine
('エンジン型式', 'engine_model', 'exact', NULL),
('engine model', 'engine_model', 'exact', NULL),
('engine / model', 'engine_model', 'synonym', 'Case 型式別シート'),
('engine [モデル]', 'engine_model', 'synonym', 'MultiOne 11.x'),
('馬力/出力', 'engine_power', 'synonym', 'Avant 縦持ち'),
('馬力_出力', 'engine_power', 'synonym', 'Avant 横持ち列名'),
('engine power', 'engine_power', 'exact', NULL),
('gross horsepower', 'engine_power', 'synonym', 'Case カタログ'),
('power (iso gross)', 'engine_power', 'synonym', 'MultiOne'),
('power', 'engine_power', 'synonym', 'Gianni Ferrari (Engine/Power)'),
('最大トルク', 'engine_torque', 'exact', NULL),
('peak torque', 'engine_torque', 'synonym', 'Case カタログ'),
('torque', 'engine_torque', 'synonym', 'MultiOne'),
('cylinder capacity', 'engine_displacement', 'synonym', 'Gianni Ferrari'),
('displacement', 'engine_displacement', 'exact', NULL),
('engine / displacement', 'engine_displacement', 'synonym', 'Case 型式別シート'),
('engine [排気量]', 'engine_displacement', 'synonym', 'MultiOne 11.x'),
('cylinders', 'engine_cylinders', 'exact', NULL),
('engine / cylinders', 'engine_cylinders', 'synonym', NULL),
('engine [気筒数]', 'engine_cylinders', 'synonym', NULL),
('fuel', 'fuel_type', 'synonym', NULL),
('engine / fuel', 'fuel_type', 'synonym', NULL),
('fuel tank capacity', 'fuel_tank_capacity', 'exact', NULL),
('engine / fuel tank capacity', 'fuel_tank_capacity', 'synonym', NULL),
('service capacities / fuel tank', 'fuel_tank_capacity', 'synonym', NULL),
-- compliance
('emissions', 'emissions_standard', 'synonym', 'Gianni Ferrari'),
('emissions certification', 'emissions_standard', 'synonym', 'Case カタログ'),
('engine / emissions certification', 'emissions_standard', 'synonym', NULL),
('emission standard', 'emissions_standard', 'synonym', 'MultiOne'),
('emission standards', 'emissions_standard', 'synonym', 'MultiOne'),
('排出ガス規格適合', 'emissions_standard', 'synonym', 'MultiOne'),
('compliant with', 'emissions_standard', 'synonym', 'MultiOne 11.x'),
-- electrical
('バッテリー容量', 'battery_capacity', 'exact', 'Avant（電動モデル）'),
('electric powertrain / battery capacity', 'battery_capacity', 'synonym', 'Case SL22EV'),
('electric powertrain / battery chemistry', 'battery_type', 'synonym', NULL),
('battery type', 'battery_type', 'exact', NULL),
('electric powertrain / nominal battery voltage', 'system_voltage', 'synonym', NULL),
('electrical / system voltage', 'system_voltage', 'synonym', NULL),
('battery voltage', 'system_voltage', 'synonym', 'Gianni Ferrari'),
('充電時間', 'charge_time', 'exact', NULL),
('electric powertrain / drive motor power', 'motor_power_drive', 'synonym', NULL),
('electric powertrain / implement motor power', 'motor_power_implement', 'synonym', NULL),
-- dimensions
('全長', 'overall_length', 'exact', NULL),
('全長_mm', 'overall_length', 'synonym', NULL),
('overall length (without bucket)', 'overall_length', 'synonym', 'Case カタログ'),
('overall dimensions / overall length / without bucket', 'overall_length', 'synonym', NULL),
('total length', 'overall_length', 'synonym', 'Case 寸法シート'),
('h - length without attachment', 'overall_length', 'synonym', 'Bobcat'),
('length with bucket', 'overall_length_with_bucket', 'synonym', NULL),
('i - length with standard bucket', 'overall_length_with_bucket', 'synonym', 'Bobcat'),
('全幅', 'overall_width', 'exact', NULL),
('全幅_mm', 'overall_width', 'synonym', NULL),
('overall dimensions / machine width', 'overall_width', 'synonym', NULL),
('overall width (without bucket)', 'overall_width', 'synonym', 'Case カタログ（脚注記号は key 生成時に除去）'),
('machine width', 'overall_width', 'synonym', 'Yanmar'),
('e - width without attachment', 'overall_width', 'synonym', 'Bobcat'),
('全高', 'overall_height', 'exact', NULL),
('全高_mm', 'overall_height', 'synonym', NULL),
('overall height', 'overall_height', 'exact', NULL),
('overall dimensions / overall height', 'overall_height', 'synonym', NULL),
('machine height', 'overall_height', 'synonym', 'Yanmar'),
('height to top of rops', 'overall_height', 'synonym', 'Case カタログ'),
('wheelbase', 'wheelbase', 'exact', NULL),
('g - wheelbase', 'wheelbase', 'synonym', 'Bobcat'),
('ground clearance', 'ground_clearance', 'exact', NULL),
('d - ground clearance', 'ground_clearance', 'synonym', 'Bobcat'),
('旋回半径_内側', 'turning_radius_inner', 'synonym', NULL),
('旋回半径内側_mm', 'turning_radius_inner', 'synonym', NULL),
('inner turning radius', 'turning_radius_inner', 'synonym', 'Case 寸法シート'),
('turning radius: inside', 'turning_radius_inner', 'synonym', 'MultiOne'),
('旋回半径_外側', 'turning_radius_outer', 'synonym', NULL),
('旋回半径外側_mm', 'turning_radius_outer', 'synonym', NULL),
('turning radius on outer edge', 'turning_radius_outer', 'synonym', 'Case 寸法シート'),
('turning radius: outside', 'turning_radius_outer', 'synonym', 'MultiOne'),
('seat height', 'seat_height', 'exact', NULL),
('max. dumping angle', 'dump_angle', 'synonym', NULL),
('max. dumping height', 'dump_height', 'synonym', NULL),
('a - articulation angle', 'articulation_angle', 'synonym', 'Bobcat'),
('c - max. reach', 'max_reach', 'synonym', 'Bobcat'),
-- performance
('リフト高', 'lift_height', 'exact', NULL),
('リフト高_mm', 'lift_height', 'synonym', NULL),
('lifting height', 'lift_height', 'synonym', NULL),
('loader performance specs / lifting height', 'lift_height', 'synonym', NULL),
('lifting/hinge pin height', 'lift_height', 'synonym', NULL),
('max. lifting height', 'lift_height', 'synonym', 'MultiOne'),
('maximum lifting height (at pin)', 'lift_height', 'synonym', 'Gianni Ferrari'),
('hinge pin height', 'lift_height', 'synonym', 'Case カタログ'),
('j - height to bucket hinge pin', 'lift_height', 'synonym', 'Bobcat'),
('リフト容量', 'lift_capacity', 'exact', NULL),
('リフト容量_kg', 'lift_capacity', 'synonym', NULL),
('lifting capacity straight, max.', 'lift_capacity', 'synonym', 'MultiOne'),
('lifting capacity, max.', 'lift_capacity', 'synonym', 'MultiOne'),
('tipping load (iso) - straight', 'tipping_load_straight', 'synonym', NULL),
('fork tipping load (iso) straight', 'tipping_load_straight', 'synonym', 'Case カタログ'),
('tipping load - straight', 'tipping_load_straight', 'synonym', NULL),
('tipping load', 'tipping_load', 'exact', 'GIANT / Yanmar。直進/屈曲の条件不明'),
('tipping load, max.', 'tipping_load', 'synonym', 'MultiOne'),
('rated operating capacity (50% of tipping load)', 'rated_operating_capacity', 'synonym', NULL),
('rated operating capacity (roc) straight - 50% of tip load', 'rated_operating_capacity', 'synonym', 'Bobcat'),
('rated operating capacity (roc) articulated - 50% of tip load', 'rated_operating_capacity_articulated', 'synonym', 'Bobcat'),
('最大ブレークアウト力', 'breakout_force', 'synonym', NULL),
('最大ブレークアウト力_kgf', 'breakout_force', 'synonym', NULL),
('breakout force', 'breakout_force', 'exact', NULL),
('最大牽引力', 'traction_force', 'synonym', NULL),
('最大牽引力_kgf', 'traction_force', 'synonym', NULL),
('pushing force', 'pushing_force', 'exact', NULL),
('最高速度', 'max_travel_speed', 'exact', NULL),
('最高速度_kmh', 'max_travel_speed', 'synonym', NULL),
('max travel speed', 'max_travel_speed', 'exact', NULL),
('max. travel speed', 'max_travel_speed', 'synonym', NULL),
('drivetrain / max. travel speed', 'max_travel_speed', 'synonym', NULL),
('max. speed', 'max_travel_speed', 'synonym', 'GIANT'),
('max speed', 'max_travel_speed', 'synonym', NULL),
('drive speed (max.)', 'max_travel_speed', 'synonym', 'MultiOne'),
('forward speed', 'max_travel_speed', 'synonym', 'Gianni Ferrari'),
('bucket capacity', 'bucket_capacity', 'exact', NULL),
('b - standard bucket width', 'bucket_width', 'synonym', 'Bobcat'),
('テレスコ搭載', 'telescopic_boom', 'synonym', NULL),
('telescopic arm', 'telescopic_boom', 'synonym', 'Gianni Ferrari'),
('telescoping boom', 'telescopic_boom', 'synonym', NULL),
('テレスコ長', 'telescopic_length', 'exact', NULL),
('テレスコ長_mm', 'telescopic_length', 'synonym', NULL),
-- hydraulics
('補助油圧流量', 'aux_hydraulic_flow', 'exact', NULL),
('補助油圧流量_lmin', 'aux_hydraulic_flow', 'synonym', NULL),
('auxiliary hydraulics flow', 'aux_hydraulic_flow', 'synonym', 'Yanmar'),
('aux. hydraulics oil flow', 'aux_hydraulic_flow', 'synonym', 'MultiOne'),
('auxiliary 1: max flow rate', 'aux_hydraulic_flow', 'synonym', 'Case カタログ'),
('hydraulics / auxiliary 1 / max. flow rate', 'aux_hydraulic_flow', 'synonym', NULL),
('auxiliary standard flow', 'aux_hydraulic_flow', 'synonym', 'Bobcat'),
('補助油圧圧力', 'aux_hydraulic_pressure', 'exact', NULL),
('補助油圧圧力_mpa', 'aux_hydraulic_pressure', 'synonym', NULL),
('補助油圧圧力_bar', 'aux_hydraulic_pressure', 'synonym', NULL),
('auxiliary hydraulics pressure', 'aux_hydraulic_pressure', 'synonym', 'Yanmar'),
('hydraulics / auxiliary 1 / pressure', 'aux_hydraulic_pressure', 'synonym', NULL),
('auxiliary high flow (optional)', 'aux_hydraulic_flow_high', 'synonym', 'Bobcat'),
('service capacities / hydraulic system', 'hydraulic_system_capacity', 'synonym', NULL),
('走行系油圧システム', 'drive_hydraulic_system', 'exact', NULL),
('作業機系油圧システム', 'work_hydraulic_system', 'exact', NULL),
-- drivetrain / accessories / others
('トランスミッション', 'transmission', 'exact', NULL),
('transmission', 'transmission', 'exact', NULL),
('transmission type', 'transmission', 'synonym', NULL),
('drivetrain / transmission type', 'transmission', 'synonym', NULL),
('標準タイヤ', 'standard_tires', 'exact', NULL),
('standard tires (tractor profile)', 'standard_tires', 'synonym', 'MultiOne'),
('standard tires [tractor profile]', 'standard_tires', 'synonym', 'MultiOne EZ'),
('standard industrial type wheels', 'standard_tires', 'synonym', 'Gianni Ferrari'),
('タイヤトレッド', 'tire_tread', 'exact', NULL),
('ホイールサイズ', 'wheel_size', 'exact', NULL),
-- basic_info
('model', 'model_name', 'synonym', NULL),
('一般的な製品分類', 'product_class', 'exact', NULL),
('sal分類', 'market_segment', 'synonym', NULL),
('動力区分', 'power_type', 'exact', NULL),
('販売状況', 'sales_status', 'exact', NULL),
('製品url', 'product_url', 'synonym', NULL),
('product url', 'product_url', 'synonym', NULL),
('product no.', 'product_code', 'synonym', 'Avant'),
('product code', 'product_code', 'exact', NULL),
('product code [standard]', 'product_code', 'synonym', 'MultiOne EZ'),
('product code (standard)', 'product_code', 'synonym', NULL),
('燃料/バッテリー', 'fuel_type', 'synonym', 'Avant。電動モデルはバッテリー情報が入ることに注意'),
('燃料_バッテリー', 'fuel_type', 'synonym', 'Avant 横持ち列名'),
('rops', 'rops_fops', 'synonym', NULL),
('fops', 'rops_fops', 'synonym', NULL);

-- ================================================================
-- 3. spec_patterns（判断を伴う対応。confidence を下げ、根拠を notes に残す）
--    pattern_id 昇順で最初に一致した規則を採用する。
-- ================================================================
INSERT INTO spec_patterns VALUES
-- 単位に基づく判別（unit_based）
(10, '^battery capacity$', 'MultiOne', NULL, '^kwh$', 'battery_capacity', 'unit_based', 0.9, 'kWh 単位 → 走行用バッテリー'),
(11, '^battery capacity$', NULL, NULL, '^ah', 'starter_battery_capacity', 'unit_based', 0.8, 'Ah 単位 → 補機バッテリーと判断'),
(12, '^engine$', 'GIANT', NULL, '^hp$', 'engine_power', 'unit_based', 0.75, 'GIANT の Engine 行は hp 数値のみ → 出力とみなす'),
(13, '^engine$', 'MultiOne', NULL, '^cc$', 'engine_displacement', 'unit_based', 0.7, 'MultiOne の Engine 行のメートル数値は排気量(cc)'),
(14, '^battery$', 'GIANT', NULL, 'ah', 'battery_capacity', 'unit_based', 0.6, 'GIANT 電動機の Battery(Ah/48V)。kWh への変換規則が無いためテキスト保持'),
-- テキスト側の Engine 行（unit なし）
(20, '^engine$', 'MultiOne', NULL, '^$', 'engine_model', 'pattern', 0.7, 'テキスト行はエンジン説明（メーカー+型式+気筒）'),
(21, '^model$', 'Gianni Ferrari', '^engine$', NULL, 'engine_model', 'pattern', 0.9, 'カテゴリ Engine 配下の Model'),
(22, '^manufacturer$', 'Gianni Ferrari', '^engine$', NULL, 'engine_manufacturer', 'pattern', 0.9, NULL),
-- Case 型式別シートの複合項目
(30, '^engine / horsepower @ .* / gross$', 'Case', NULL, NULL, 'engine_power', 'pattern', 0.8, '回転数条件は notes に残る（項目名に含まれる）'),
(31, '^engine / peak torque @', 'Case', NULL, NULL, 'engine_torque', 'pattern', 0.8, '回転数条件付き'),
(32, '^engine / engine speeds rpm / rated - full load$', 'Case', NULL, NULL, 'rated_engine_speed', 'pattern', 0.8, NULL),
(33, 'tipping load.*straight', NULL, NULL, NULL, 'tipping_load_straight', 'pattern', 0.8, 'straight を含む転倒荷重'),
(34, 'tipping load.*articulated|articulated.*tipping load', NULL, NULL, NULL, 'tipping_load_articulated', 'pattern', 0.8, NULL),
(35, 'roc.*straight|straight.*roc', NULL, NULL, NULL, 'rated_operating_capacity', 'pattern', 0.75, 'ROC 直進系のばらつき表記'),
(36, 'roc.*articulated|articulated roc', NULL, NULL, NULL, 'rated_operating_capacity_articulated', 'pattern', 0.75, NULL),
(37, '^loader performance specs / rated operating capacity / 50% of tipping load$', 'Case', NULL, NULL, 'rated_operating_capacity', 'pattern', 0.75, NULL),
(38, 'warranty', NULL, NULL, NULL, 'warranty', 'pattern', 0.8, '保証系はまとめて warranty へ'),
(40, 'charging time 0 - 100', 'Case', NULL, NULL, 'charge_time', 'pattern', 0.7, '0-100% 充電時間を代表値とする。オン/オフボードの区別は項目名に残る'),
-- 速度のレンジ付き表記（高速側を最高速度とみなす）
(50, '^travel speed - high range$', 'Bobcat', NULL, NULL, 'max_travel_speed', 'inferred', 0.7, '高速レンジ側を最高速度とみなす'),
(51, '^max\. speed high$', 'GIANT', NULL, NULL, 'max_travel_speed', 'inferred', 0.7, NULL),
(52, '^drive speed \(max\.\) - high$', 'MultiOne', NULL, NULL, 'max_travel_speed', 'inferred', 0.7, NULL),
(53, '^drive speed \(max\.\) - 2 speed \[high\]$', 'MultiOne', NULL, NULL, 'max_travel_speed', 'inferred', 0.7, NULL),
(54, 'max. travel speed / rabbit$', 'Case', NULL, NULL, 'max_travel_speed', 'inferred', 0.7, 'Rabbit=高速レンジ'),
(55, 'max. travel speed / rabbit - high gear$', 'Case', NULL, NULL, 'max_travel_speed', 'inferred', 0.65, NULL),
(56, '^forward speed high$', 'Gianni Ferrari', NULL, NULL, 'max_travel_speed', 'inferred', 0.7, NULL),
-- 意味が近いが完全一致ではない項目（inferred、要レビュー）
(60, '^working hydraulics$', 'GIANT', NULL, NULL, 'aux_hydraulic_flow', 'inferred', 0.6, 'GIANT の作業油圧流量。補助油圧流量に相当すると判断（要レビュー）'),
(62, '^system relief at quick couplers$', 'Bobcat', NULL, NULL, 'aux_hydraulic_pressure', 'inferred', 0.7, 'カプラ部リリーフ圧を補助油圧圧力とみなす'),
(63, '^f - cab height$', 'Bobcat', NULL, NULL, 'overall_height', 'inferred', 0.7, 'キャブ高を全高とみなす（要レビュー）'),
(64, '^width on standard tires$', 'Case', NULL, NULL, 'overall_width', 'inferred', 0.8, '標準タイヤでの全幅'),
(65, '^max. height with safety roof$', 'Case', NULL, NULL, 'overall_height', 'inferred', 0.8, 'ROPS 上端の全高'),
(66, '^weight without equipment with rops$', 'Gianni Ferrari', NULL, NULL, 'operating_weight', 'inferred', 0.8, 'ROPS 仕様・装備なし質量を運転質量とみなす'),
(67, '^weight without equipment with cab$', 'Gianni Ferrari', NULL, NULL, 'operating_weight_enclosed', 'inferred', 0.8, NULL),
(68, '^maximum overhang \(at mounting plate\)$', 'Gianni Ferrari', NULL, NULL, 'max_reach', 'inferred', 0.7, 'オーバーハングをリーチ相当とみなす'),
(69, '^driving mechanism$', 'GIANT', NULL, '^kw$', 'motor_power_drive', 'inferred', 0.6, '電動機の走行機構出力'),
(70, '^working hydraulics motor$', 'GIANT', NULL, '^kw$', 'motor_power_implement', 'inferred', 0.6, NULL),
(71, '^breakout force / 50 cm', 'MultiOne', NULL, NULL, 'breakout_force', 'pattern', 0.85, '測定条件 50cm 付き'),
(72, '^pushing force', NULL, NULL, NULL, 'pushing_force', 'pattern', 0.9, '脚注記号付き表記を吸収'),
(73, '^average ground pressure', NULL, NULL, NULL, 'ground_pressure', 'pattern', 0.85, 'w/standard tires 等の条件付き'),
(74, '^operation time', 'MultiOne', NULL, NULL, 'operation_time', 'pattern', 0.8, 'ECO/POWER モード別の行がある'),
(75, '^displacement/cylinders$', 'Case', NULL, NULL, 'engine_displacement', 'pattern', 0.7, '排気量と気筒数の複合表記。排気量として扱う'),
(76, '^出力規格$', 'Avant', NULL, NULL, 'engine_power', 'pattern', 0.95, '「14.9 kW (20 hp)」形式から公式 kW を採用（hp 換算の 馬力/出力 より優先）'),
(78, '^lifting height$', NULL, NULL, NULL, 'lift_height', 'pattern', 0.85, 'GIANT/Case 寸法シート等。ヒンジピン高さと推定'),
(79, '^horsepower$', 'Bobcat', NULL, NULL, 'engine_power', 'pattern', 0.85, NULL),
(80, '^charging time', 'MultiOne', NULL, NULL, 'charge_time', 'pattern', 0.7, NULL),
(81, '^dump height', NULL, NULL, NULL, 'dump_height', 'pattern', 0.8, '45°ダンプ時等の条件は項目名に残る'),
(82, '^engine$', 'Case', NULL, '^$', 'engine_model', 'pattern', 0.7, 'カタログの Engine 行はエンジン型式のテキスト');

-- ================================================================
-- 4. unit_conversions（明示的な変換のみ。from_unit は psn_unit_key() 適用後）
--    同一単位の恒等変換も登録する（変換可否の判定を単純化するため）。
-- ================================================================
INSERT INTO unit_conversions VALUES
-- 質量 → kg
('kg', 'kg', 1.0, NULL),
('lb', 'kg', 0.45359237, NULL),
('lbs', 'kg', 0.45359237, NULL),
-- 長さ → mm
('mm', 'mm', 1.0, NULL),
('cm', 'mm', 10.0, NULL),
('m', 'mm', 1000.0, NULL),
('in', 'mm', 25.4, NULL),
('ft', 'mm', 304.8, NULL),
-- 速度 → km/h
('km/h', 'km/h', 1.0, NULL),
('kmh', 'km/h', 1.0, NULL),
('kph', 'km/h', 1.0, NULL),
('km/hr', 'km/h', 1.0, NULL),
('mph', 'km/h', 1.609344, NULL),
('mp/h', 'km/h', 1.609344, '原文の誤記表記'),
-- 流量 → L/min
('l/min', 'L/min', 1.0, NULL),
('lmin', 'L/min', 1.0, NULL),
('lpm', 'L/min', 1.0, NULL),
('gpm', 'L/min', 3.785411784, 'US ガロン'),
-- 圧力 → MPa
('mpa', 'MPa', 1.0, NULL),
('bar', 'MPa', 0.1, NULL),
('psi', 'MPa', 0.00689476, NULL),
-- 出力 → kW
('kw', 'kW', 1.0, NULL),
('hp', 'kW', 0.745699872, '機械馬力'),
('cv', 'kW', 0.735499, 'メートル馬力'),
-- トルク → Nm
('nm', 'Nm', 1.0, NULL),
('lbft', 'Nm', 1.355818, NULL),
('lb-ft', 'Nm', 1.355818, NULL),
('ftlb', 'Nm', 1.355818, NULL),
-- 力 → kN
('kn', 'kN', 1.0, NULL),
('n', 'kN', 0.001, NULL),
('kgf', 'kN', 0.00980665, NULL),
('lbf', 'kN', 0.004448222, NULL),
('lbs', 'kN', 0.004448222, '力の文脈での lbs（canonical 側が kN のときのみ適用）'),
('lb', 'kN', 0.004448222, NULL),
-- 排気量 → cc
('cc', 'cc', 1.0, NULL),
('cm3', 'cc', 1.0, NULL),
('l', 'cc', 1000.0, NULL),
('in3', 'cc', 16.387064, NULL),
-- 体積 → m3
('m3', 'm3', 1.0, NULL),
('cuyd', 'm3', 0.764554858, NULL),
('yd3', 'm3', 0.764554858, NULL),
-- 容量 → L
('l', 'L', 1.0, NULL),
('liters', 'L', 1.0, NULL),
('litres', 'L', 1.0, NULL),
('gal', 'L', 3.785411784, 'US ガロン'),
('qt', 'L', 0.946352946, NULL),
-- エネルギー → kWh
('kwh', 'kWh', 1.0, NULL),
-- 時間 → h
('h', 'h', 1.0, NULL),
('hr', 'h', 1.0, NULL),
('hrs', 'h', 1.0, NULL),
('min', 'h', 0.0166666667, NULL),
-- 接地圧 → kg/m2
('kg/m2', 'kg/m2', 1.0, NULL),
('kg/m²', 'kg/m2', 1.0, NULL),
('lbs/sqft', 'kg/m2', 4.88242764, NULL),
-- 角度 → °
('°', '°', 1.0, NULL),
('deg', '°', 1.0, NULL),
('degrees', '°', 1.0, NULL),
-- 電気
('v', 'V', 1.0, NULL),
('volts', 'V', 1.0, NULL),
('a', 'A', 1.0, NULL),
('amp', 'A', 1.0, NULL),
('ah', 'Ah', 1.0, NULL),
('ahr', 'Ah', 1.0, NULL),
-- その他
('cyl', 'cyl', 1.0, NULL),
('cylinder', 'cyl', 1.0, NULL),
('cylinders', 'cyl', 1.0, NULL),
('rpm', 'rpm', 1.0, NULL);
